# Generated by Django 2.0.6 on 2019-03-05 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('Password1', models.CharField(max_length=70)),
                ('Password2', models.CharField(max_length=70)),
                ('dateAccountCreated', models.DateField(verbose_name=datetime.datetime(2019, 3, 5, 15, 44, 9, 450928, tzinfo=utc))),
            ],
        ),
    ]
