# Generated by Django 2.0.6 on 2019-03-05 16:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('developer', models.CharField(max_length=70)),
                ('dateMade', models.DateTimeField()),
                ('ageLimit', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamecollector',
            name='userTableForeginKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamecollector',
            name='dateAccountCreated',
            field=models.DateField(default=datetime.datetime(2019, 3, 5, 16, 6, 14, 669518, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='game',
            name='gameCreator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gameApp.GameCollector'),
        ),
    ]
