# Generated by Django 2.0.6 on 2019-03-05 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0002_auto_20190305_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecollector',
            old_name='userTableForeginKey',
            new_name='userTableForeignKey',
        ),
        migrations.AlterField(
            model_name='gamecollector',
            name='dateAccountCreated',
            field=models.DateField(default=datetime.datetime(2019, 3, 5, 16, 20, 3, 368849, tzinfo=utc)),
        ),
    ]
