# Generated by Django 2.0.6 on 2019-03-05 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0004_auto_20190305_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecollector',
            name='dateAccountCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
