# Generated by Django 2.0.6 on 2019-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0005_auto_20190305_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dateMade',
            field=models.DateField(),
        ),
    ]
