# Generated by Django 2.0.6 on 2019-03-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0006_auto_20190306_0845'),
        ('gameApp', '0006_auto_20190305_2243'),
    ]

    operations = [
    ]
